module.exports = {
  name: 'course-enrollment',
  label: 'Course Enrollment',
  icon: 'school',
  category: 'Custom',
  properties: {
    scriptUrl: {
      label: 'Bundle URL',
      type: 'Text',
      bindable: true,
      defaultValue: '',
      section: 'Setup',
      helper: 'URL to your IIFE bundle that defines window.CourseEnrollmentMount.',
    },
    semesters: { label: 'Semesters', type: 'Object', bindable: true, defaultValue: [], section: 'Data' },
    selectedSemesterIndex: { label: 'Selected Semester Index', type: 'Number', bindable: true, defaultValue: 0, section: 'Data' },
    selectedDayIndex: { label: 'Selected Day Index', type: 'Number', bindable: true, defaultValue: 0, section: 'Data' },
    searchQuery: { label: 'Search Query', type: 'Text', bindable: true, defaultValue: '', section: 'Data' },
    height: { label: 'Height (px)', type: 'Number', defaultValue: 700, section: 'Appearance' },
    background: { label: 'Background', type: 'Text', defaultValue: '#ffffff', section: 'Appearance' },
  },
  triggerEvents: [
    { name: 'noteAdded', label: 'Note Added' },
    { name: 'noteDeleted', label: 'Note Deleted' },
    { name: 'noteToggledProblem', label: 'Note Toggled Problem' },
    { name: 'noteToggledResolved', label: 'Note Toggled Resolved' },
    { name: 'childMoved', label: 'Child Moved To Course' },
    { name: 'movedToWaitingList', label: 'Child Moved To Waiting List' },
    { name: 'courseApprovalToggled', label: 'Course Approval Toggled' },
    { name: 'courseFullToggled', label: 'Course Full/Closed Toggled' },
    { name: 'autoEnrollTriggered', label: 'Auto Enroll Triggered' },
    { name: 'resetToFirstChoices', label: 'Reset To First Choices Triggered' },
  ],
};
